user root;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /usr/local/openresty/nginx/conf/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name hermes-app-5.nexuslbs.org _;

        root /mnt/host;

        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;

        location = /favicon.ico {
            alias /etc/nginx/favicon.ico;
            add_header Cache-Control "public, max-age=86400";
        }

        location ~ \.md$ {
            try_files $uri =404;
            content_by_lua_file /etc/nginx/markdown.lua;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
