x-logging:
  logging: &logging
    options:
      max-size: 50m

networks:
  hermes-net:
    external: true
    name: hermes-net
  lvg:
    driver: bridge
    internal: true

volumes:
  loki-vol:
    name: loki
  grafana-vol:
    name: grafana
  prometheus-vol:
    name: prometheus

services:
  vector:
    container_name: hermes-vector
    build:
      context: vector
      dockerfile: Dockerfile
      args:
        VECTOR_IMAGE: timberio/vector:0.55.0-debian
    restart: unless-stopped
    volumes:
      - /var/log/journal:/var/log/journal:ro
      - /run/systemd/journal:/run/systemd/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /opt/data/backup/vector:/var/lib/vector:rw
    user: "0"
    networks:
      - lvg
    depends_on:
      - loki
    mem_limit: 500M
    logging: *logging

  loki:
    container_name: hermes-loki
    build:
      context: loki
      dockerfile: Dockerfile
      args:
        LOKI_IMAGE: grafana/loki:3.7.2
    restart: unless-stopped
    volumes:
      - loki-vol:/loki:rw
    networks:
      - lvg
    command: -config.file=/etc/loki/loki-config.yaml
    mem_limit: 500M
    logging:
      driver: journald

  grafana:
    container_name: hermes-grafana
    build:
      context: grafana
      dockerfile: Dockerfile
      args:
        GRAFANA_IMAGE: grafana/grafana:13.0.1
    restart: unless-stopped
    env_file:
      - /opt/data/credentials/services.env
    volumes:
      - grafana-vol:/var/lib/grafana:rw
      - /opt/data/backup/grafana:/opt/data/backup/grafana:rw
    networks:
      - hermes-net
      - lvg
    ports:
      - 3000:3000
    depends_on:
      - loki
    mem_limit: 500M
    logging:
      driver: journald

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: hermes-cadvisor
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - hermes-net
    mem_limit: 200M
    logging:
      driver: journald

  prometheus:
    build:
      context: prometheus
      dockerfile: Dockerfile
    container_name: hermes-prometheus
    restart: unless-stopped
    extra_hosts:
      - 'host:host-gateway'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - prometheus-vol:/prometheus:rw
    networks:
      - hermes-net
    mem_limit: 500M
    logging:
      driver: journald
